### ISSUE TITLE
a compatible flash cartiage could not be auto-detected

### ISSUE THREAD

**Issue by DrpugSlug** [lesserkuma/FlashGBX#108]
I try to write rom to my gba cartiage but it keep popping this up

**Comment by LucentW** [comment]
Can you please send a picture of your GBxCart with the cart plugged in, cartridge (preferably opened to identify the flash chip) and screenshot of the FlashGBX GUI?

**Comment by DrpugSlug** [comment]
![image_2024-03-14_183629035](https://github.com/lesserkuma/FlashGBX/assets/88154324/5d311140-d896-4deb-ae5c-b480b5b0db6c)
![IMG_2489](https://github.com/lesserkuma/FlashGBX/assets/88154324/edebf753-6633-4553-aab6-bb67f79b65da)

**Comment by LucentW** [comment]
You can't reflash original cartridges: they don't have a flash chip but an etched mask ROM.

**Comment by DrpugSlug** [comment]
where can i find those

**Comment by LucentW** [comment]
All modern cheap bootleg/clone cartridges fit the bill, you can check AliExpress if you want something to fiddle with.
If you're looking for carts i.e. with 1Mbit flash save + real time clock for Gen3 Pokémon and romhacks, you'd better fetch one of insideGadgets' carts that got them both rather than relying on cheap carts.

A good resource to check out with an extensive, but not omnicomprensive (considering bootleggers release new carts every month or so depending on chip stocks), list of flashcarts is [Flash Cart DB](https://flashcartdb.com/index.php/Main_Page).
