### ISSUE TITLE
New Cart or what else?

### ISSUE THREAD

**Issue by x7l7j8cc** [lesserkuma/FlashGBX#23]
Ive just received this cart but dont know if already exist or not since i dont find any info about it...
![IMG_20220111_213430](https://user-images.githubusercontent.com/526407/149017333-4c014293-a4b7-44d7-a719-180df03da7df.jpg)

I can Flash and read the Rom without problem with 
"2006_TSOP_64BALL_QFP48 with AL016J55FFAR2 (or compatible)" Cart Type.

Here the Detect Cart Info:

> Game Title: POKEMON_GLDAAUE
ROM Size: 2 MB
Save Type: 256K SRAM (32 KB)
Flash ID Check (voltage limited):
[     ROM     ] F3 C3 00 01 00 00 00 00 
[WR   / AAA/A9] 02 02 4A 4A 00 00 15 15 
[WR   /4AAA/A9] 02 02 4A 4A 00 00 15 15 
[WR   /7AAA/A9] 02 02 4A 4A 00 00 15 15 
Common Flash Interface Data:
Swapped pins: (0, 1)
Device size: 0x0200000 (2.00 MB)
Voltage: 2.7–3.6 V
Single write: True
Buffered write: False
Sector erase: 512–8192 ms
Sector flags: As shown (0x02)
Region 1: 0x0000000–0x0003FFF @ 0x4000 Bytes × 1
Region 2: 0x0004000–0x0007FFF @ 0x2000 Bytes × 2
Region 3: 0x0008000–0x000FFFF @ 0x8000 Bytes × 1
Region 4: 0x0010000–0x01FFFFF @ 0x10000 Bytes × 31
Compatible Cartridge Types:
2006_TSOP_64BALL_QFP48 with AL016J55FFAR2*
SD007_BV5_V3 with AM29LV160MB
SD007_TSOP_29LV017D with L017D70VC
SD007_TSOP_48BALL with AM29LV160DB
SD007_TSOP_48BALL with AM29LV160DT
SD007_TSOP_48BALL with L160DB12VI
SD007_TSOP_64BALL_SOP28 with unlabeled flash chip
FlashGBX v3.3 | GBxCart RW v1.3 – Firmware L1 (COM5)

There is the SRAM, but obviously dont save correctly with standard roms, without battery.
But the ROMs contained save without problem, but i think they re-programmed the rom to save in ROM.

**Comment by LucentW** [comment]
Do you have a GBxCart to poll the CFI off that cartridge or at least the flash ID?
The flash chip looks like it has been sanded, so with no markings @lesserkuma can't really find the datasheet for that chip and implement it in FlashGBX :(

**Comment by x7l7j8cc** [comment]
@LucentW I've inserted the photo from the phone first, then i continued to write from the computer.

**Comment by LucentW** [comment]
Well, even though the cartridge types don't match the PCB markings, 99.9% you should be able to flash it with any of those profiles.
Quite strange that the flash chip is 2 MB only on a batteryless save cart -- usually the bootleggers opt for 4 MB because of the chips' large sector size (and obviously the same sector erase size).

You can contribute PCB pics on the [FlashcartDB](https://flashcartdb.com/index.php/Main_Page) Wiki and @lesserkuma will update the supported carts list with the markings on your cart when you confirm that it flashes cleanly.

**Comment by x7l7j8cc** [comment]
@LucentW I've already write that i flashed successfully a game, the game flashed was Pokemon Crystal Clear.

Plays very smoothly, and i think this might have the SRAM onboard but no battery pin as far i can see.
Because when i save and soft-reset there still the save there, but if i turn off completely my GameBoy the save is gone.

**Comment by LucentW** [comment]
That cart is too small to fit Crystal Clear and the batteryless patch (for the reasons explained before -- there's no empty 0x10000 bytes segment + a bank for the read/save routines to sacrifice), you need a 4 MB cart for that.
If you want to go for the battery backed solution, Perfect Dark and Pokémon TCG2 carts are best bet since both are 4 MB ROMs and the bootleggers don't bother patching them, so you should also get a cart with a moderately power efficient SRAM chip, battery retainer and preinstalled CR2032.

**Comment by x7l7j8cc** [comment]
@LucentW  Obviously i mean a Clean Pokemon Crystal Clear (not patched).
And this because i opened after i flashed the ROM to see inside. 

I dont want to patch the game, i want to add a battery XD If i can. There's plenty room to put a battery.
But first i need to find the correct 3V pin for the SRAM.

**Comment by lesserkuma** [comment]
That cartridge looks like it was not designed to work with a battery as there are no battery terminals.
