### ISSUE TITLE
Can't backup save data from SD007_TS0P_64BALL_S0P28

### ISSUE THREAD

**Issue by fabiodelgadopereira** [lesserkuma/FlashGBX#39]
I can't backup save data from **SD007_TS0P_64BALL_S0P28**

Which option do I select in the combobox "**save type**" and "**mapper type**"?

![20220528_174215](https://user-images.githubusercontent.com/38516312/170844360-8e380273-7fdf-40d8-bd38-2b271cd5151f.jpg)
![Capturar](https://user-images.githubusercontent.com/38516312/170844362-f64594ee-cea3-407a-a0bc-8c1e646ce245.PNG)

**Comment by LucentW** [comment]
Hi Fábio,
that cartridge is using batteryless saving, so it means that the SRAM chip there is actually empty and used only as a staging area so that the routines the bootleggers added to the game reflash the SRAM into the game ROM.

You need to dump the entirety of the ROM (do a Detect Flash Cart first to recognize the real flash size), pop it into an emulator with a debugger like BGB to identify the ROM location where the save is, then extract it manually using an hex editor. You can then edit it and paste it back into the same location again and reflash it to the cart to change the save.

**Comment by fabiodelgadopereira** [comment]
Thanks! Using BGB I was able to export the save
