### ISSUE TITLE
"No devices found" on Linux

### ISSUE THREAD

**Issue by Anonymous941** [lesserkuma/FlashGBX#65]
I've installed the qt5 version of the software and added my user to the `dialout` group, but when I run the app, even as root, it says "No devices found".  I tested the flasher on another computer and it works, and the light turns on when I connect it, but somehow the computer fails to connect it.  I am using Ubuntu.

**Comment by lesserkuma** [comment]
That sounds like an issue caused by a process called `brttly` (a braille display driver) intercepting and taking over control of each and every connected USB device that use the CH340/341 chipset. Unfortunately it comes pre-installed with many linux distributions and removing it usually fixes the issue. The pre-compiled linux builds take care of this as far as I know.

**Comment by Anonymous941** [comment]
> That sounds like an issue caused by a process called `brttly` (a braille display driver) intercepting and taking over control of each and every connected USB device that use the CH340/341 chipset. Unfortunately it comes pre-installed with many linux distributions and removing it usually fixes the issue. The pre-compiled linux builds take care of this as far as I know.

Maybe you should add something in the README about that...

**Comment by lesserkuma** [comment]
OK I will!
