### ISSUE TITLE
FlashGBX No device found when trying to connect.

### ISSUE THREAD

**Issue by devicemodder** [lesserkuma/FlashGBX#69]
Hello, I have a GBxCart RW V1.4 that i am trying to use with the latest flashGBX software. The issue is that the software can't see the GBx board. it shows up in device manager as COM1, so i dunno where the issue is. Running windows 11 and installed the drivers for the CH340.

This worked previously on my windows 10 machine with FlashGBX 2.8.

I am running the latest version of FlashGBX as of this post.

**Comment by lesserkuma** [comment]
Hello! Can you post a photo of your GBxCart RW device so the exact model can be determined?
You can also join insideGadgets’ Discord at https://gbxcart.com/discord for hardware and driver troubleshooting.

**Comment by devicemodder** [comment]
I'll post when I get home from work

**Comment by devicemodder** [comment]
![20230216_162633](https://user-images.githubusercontent.com/56454699/219491213-da4104a4-9d26-41be-9505-5600a938335a.jpg)
![20230216_162645](https://user-images.githubusercontent.com/56454699/219491219-c72f7649-28d0-4561-9977-64632f1425ce.jpg)

**Comment by lesserkuma** [comment]
Seems fine and I see no damage. Can you try some different USB data cables and USB ports? Just to be sure!

**Comment by devicemodder** [comment]
I only have one other cable with me at the moment, tried it and i get the same... 

hrm... device manager has a bunch of bluetooth serial devices. i disable them and get: 

![sdd](https://user-images.githubusercontent.com/56454699/219501560-a7c9c4a8-9d6b-4cd6-b42a-5e3cd711f25b.png)

**Comment by devicemodder** [comment]
COM3 is the GBx Cart RW

**Comment by lesserkuma** [comment]
I think after pulling a list of all devices from the operating system, it detected the GBxCart RW on COM3, but when trying to actually connect to it, it’s no longer there. Might be a loose connection or otherwise unstable. I’d try more different cables and different USB ports. Also give this software a try: https://shop.insidegadgets.com/wp-content/uploads/2018/05/GBxCart_RW_GUI_Interface_v1.49.zip

If it still doesn’t work even with the other GUI software, it should be unrelated to this software and more likely an issue with the device, cables, drivers, operating system or USB controller. Please contact insideGadgets in that case.

**Comment by devicemodder** [comment]
Ok, I'll check it out.

**Comment by happysoul** [comment]
Maybe your GBxCart has a broken chip （6pin use for switch 5v 3.3v）
When you connect cart to GBxCart，Cart pin 1 may connect to GBxCart pin 1 & 2
pin1 = vcc , 3.3v
pin2 = clk , connect to GND on GBxCart

when connect/disconnect cart to GBxCart 
it happens looks like this |/|  
board pin | | 
cart pin / 
If short circuit ，GBxCart chip burn down. atmega8515 may not work because of vcc pin got 100Ω to GND

Test GBxCart pin1, if it is 3.3v ,not gnd
