### ISSUE TITLE
Mac & Linux version not in releases

### ISSUE THREAD

**Issue by maxoakland** [lesserkuma/FlashGBX#8]
Only the Windows version is available pre-compiled in releases

**Comment by LucentW** [comment]
You do not need a prebuilt version on Linux and macOS since you can just get it [from pip directly](https://github.com/lesserkuma/FlashGBX#installing-and-running) as long as you have Python 3 intstalled, by using the command `pip install FlashGBX`. You can use `pip` on Windows too.

On Linux you can even just `git clone` the repository and pair it with its dependencies, namely pySide2 and pySerial.

**Comment by maxoakland** [comment]
I’m on Mac. I’ll see if I can figure compiling with your instructions. Once I compile it do you want me to send you the compiled file so you have one for other users?

**Comment by lesserkuma** [comment]
Adding to what @LucentW was very kind to explain, it also seems like a PyInstaller package for macOS can only be created using a macOS device. As I do not own a macOS device, I’m afraid it’s impossible for the time being. But I hope the [Python/pip way](https://github.com/lesserkuma/FlashGBX#installing-and-running) works for you!

**Comment by maxoakland** [comment]
> Adding to what @LucentW was very kind to explain, it also seems like a PyInstaller package for macOS can only be created using a macOS device. As I do not own a macOS device, I’m afraid it’s impossible for the time being. But I hope the [Python/pip way](https://github.com/lesserkuma/FlashGBX#installing-and-running) works for you!

I'm going to try it. If it works, I can give you the package I made
